version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: edit-novel:latest       # tag local để Portainer quản lý
    container_name: edit-novel
    env_file:
      - stack.env                  # nếu dùng env, file này phải nằm trong repo
    ports:
      - "8088:8000"
    restart: unless-stopped
    pull_policy: build             # ép Docker build thay vì cố pull image không tồn tại
    # healthcheck (nếu có endpoint khỏe):
    # healthcheck:
    #   test: ["CMD", "wget", "-qO-", "http://localhost:8000/healthz"]
    #   interval: 30s
    #   timeout: 3s
    #   retries: 5
